# Generated by Django 3.2.5 on 2021-07-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='anoPublicaçao',
            new_name='anoPublicacao',
        ),
    ]
